### ISSUE TITLE
No Longer Working on iOS 13.1.2 (Released September 30th)

### ISSUE THREAD

**Issue by TheBroox** [51Degrees/Renderer#3]
I am looking into it now to determine what has changed but Apple seems to have changed something with iOS 13.1.2 that prevents this detection method from working.

**Comment by Steve51D** [comment]
Hi, You're correct. The rendering engine changed sufficiently with iOS 13 that we needed additional data to correctly determine the device. We've got an update that is coincidentally ready to go and we'll be deploying here shortly.
This also adds the new iPhone 11 family and iPad 7 devices.
