### ISSUE TITLE
Fields are not getting populated with the device data

### ISSUE THREAD

**Issue by atrunelle** [51Degrees/Renderer#4]
Thanks for sharing your solution to detect devices, specially for Apple devices on latest iOS versions!

The following URL seems to be sending a 406:  https://cloud.51degrees.com/api/v4/resource.js?values=javascripthardwareprofile+devicetype+hardwarevendor+hardwarename+platformname+platformversion+browsername+browserversion

I don't know if related, but when trying it out, only the `Renderer(s)` and` Image Hash` field gets populated.

![screencapture-file-Users-auroretrunelle-projects-51degree-device-detection-index-html-2019-12-27-16_05_16](https://user-images.githubusercontent.com/17130395/71523977-58192c80-28c3-11ea-8a64-f05d3c2d0f8b.png)

Should the other not be populated as well?

**Comment by Steve51D** [comment]
Hi @atrunelle 

We've recently made some breaking changes to our v4 cloud service and haven't updated this repository just yet. I'll add it to our backlog to ensure it does not get forgotten. 
I'll hopefully get time to look into it in the next couple of days.

Thanks,
Steve.

**Comment by Joseph51D** [comment]
Hi @atrunelle,

There appears to be a problem with older iOS versions <=10.x which we're looking into, can you confirm the iOS version of the devices you are testing with?

Regards,
Joe

**Comment by atrunelle** [comment]
Hi @Joseph51D,

I have been testing on iOS 12 and 13 as the latest as what I am the most interested to test with. Your solution is most valuable on iOS >= 12.3 as it's when other detecting gets difficult. Also, ideally, it will work with any version.

**Comment by Joseph51D** [comment]
Hi @atrunelle,

Thanks for the update, we have had this tested and working on iOS versions 12 and 13. It would be very helpful if you could share with us the exact versions of iOS you've been using. 

Regards,
Joe

**Comment by atrunelle** [comment]
Hi @Joseph51D ,

I had another look after pulling the latest and it seems to be working since you updated the URL. I must have done something wrong with the URL I generated.

Thanks for updating the example, I think you can close this if you want. 😄

**Comment by Steve51D** [comment]
Thanks @atrunelle.
