### ISSUE TITLE
iphone 12 getRender return "A15 GPU"

### ISSUE THREAD

**Issue by QDHello** [51Degrees/Renderer#7]
iphone 12 CPU is "A14 GPU", It is suppose to return A14,but return A15; And also Iphone 13 mini return A14 | A15，it suppose to be A15.

**Comment by QDHello** [comment]
may you help me check it out, thank you!

**Comment by jwrosewell** [comment]
Does this relate to the information returned from the iPhone or the results of this library?

**Comment by Steve51D** [comment]
Hi @QDHello,

We've recently made some changes to the scripts, could you confirm if you are still experiencing this issue?

Thanks,
Steve.
